### ISSUE TITLE
Binding won't start after 1.1.1 libraries were added

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/org.openhab.binding.zigbee#248]
I've tried a regular install, a manual install, I've updated to the latest OH snapshot (1348), but I can't get the most recent snapshot version of the binding to start.  Is #239 needed? Exceptions:

```
2018-09-04 05:05:09.478 [ERROR] [org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.initialize()' on 'org.openhab.binding.zigbee.ember.handler.EmberHandler@1c14f6f4': com/zsmartsystems/zigbee/ZigBeeKey
java.lang.NoClassDefFoundError: com/zsmartsystems/zigbee/ZigBeeKey
        at org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler.initialize(ZigBeeCoordinatorHandler.java:231) ~[?:?]
        at org.openhab.binding.zigbee.ember.handler.EmberHandler.initialize(EmberHandler.java:55) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor201.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [107:org.eclipse.smarthome.core:0.10.0.201808242044]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [107:org.eclipse.smarthome.core:0.10.0.201808242044]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.ClassNotFoundException: com.zsmartsystems.zigbee.ZigBeeKey cannot be found by org.openhab.binding.zigbee_2.4.0.201809021943
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387) ~[?:?]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:?]
        ... 11 more
2018-09-04 05:05:09.484 [ERROR] [org.eclipse.smarthome.core.thing.internal.ThingManager] - Exception occurred while initializing handler of thing 'zigbee:coordinator_ember:9b51c72d': com/zsmartsystems/zigbee/ZigBeeKey
java.lang.NoClassDefFoundError: com/zsmartsystems/zigbee/ZigBeeKey
        at org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler.initialize(ZigBeeCoordinatorHandler.java:231) ~[?:?]
        at org.openhab.binding.zigbee.ember.handler.EmberHandler.initialize(EmberHandler.java:55) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor201.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [107:org.eclipse.smarthome.core:0.10.0.201808242044]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [107:org.eclipse.smarthome.core:0.10.0.201808242044]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.ClassNotFoundException: com.zsmartsystems.zigbee.ZigBeeKey cannot be found by org.openhab.binding.zigbee_2.4.0.201809021943
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387) ~[?:?]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:?]
        ... 11 more
```
The log ends with...
```
2018-09-04 04:52:14.401 [DEBUG] [org.openhab.binding.zigbee.ember] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.thing.binding.ThingHandlerFactory}={service.id=620, service.bundleid=18, service.scope=bundle, component.name=org.openhab.binding.zigbee.ember.internal.EmberHandlerFactory, component.id=476} - org.openhab.binding.zigbee.ember
2018-09-04 04:52:14.410 [DEBUG] [org.openhab.binding.zigbee.ember] - ServiceEvent REGISTERED - {org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler}={service.id=621, service.bundleid=18, service.scope=singleton} - org.openhab.binding.zigbee.ember
2018-09-04 04:52:14.414 [DEBUG] [org.openhab.binding.zigbee.ember] - ServiceEvent REGISTERED - {org.eclipse.smarthome.core.thing.binding.firmware.FirmwareUpdateHandler}={service.id=622, service.bundleid=18, service.scope=singleton} - org.openhab.binding.zigbee.ember
2018-09-04 04:52:14.425 [DEBUG] [org.openhab.binding.zigbee.ember.handler.EmberHandler] - Initializing ZigBee Ember serial bridge handler.
2018-09-04 04:52:14.427 [DEBUG] [org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Initializing ZigBee network [zigbee:coordinator_ember:9b51c72d].
2018-09-04 04:52:14.427 [DEBUG] [org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Channel 25
2018-09-04 04:52:14.427 [DEBUG] [org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - PANID <panid removed>
2018-09-04 04:52:14.427 [DEBUG] [org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - EPANID <epanid removed>
2018-09-04 04:52:14.428 [DEBUG] [org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Key <key removed>
2018-09-04 04:52:14.429 [DEBUG] [org.openhab.binding.zigbee.handler.ZigBeeCoordinatorHandler] - Key String <key removed>
```

**Comment by cdjackson** [comment]
This should now be resolved.
