### ISSUE TITLE
Displaying zigbee nodes in CLI does fail with NullPointerException

### ISSUE THREAD

**Issue by yuergen** [openhab/org.openhab.binding.zigbee#686]
### Outline
Displaying the nodes in the ZigBee network does fail with a NullPointerException.

My understanding from a different bug report (or forum post, I cannot find it anymore) is that this might be caused by the ZigBee binding's XML files. Attaching the files here does not work, however I have uploaded them to a gist: (https://gist.github.com/yuergen/4d24abd372f037da0b9c1d4594fc0d60)

### Configuration

| Configuration    | Description                                                                    |
|------------------|--------------------------------------------------------------------------------|
| Coordinator used | Smabit AV2010/10 / Ember                                                         |
| openHAB version  |  3.2.0M3    |
| Hardware         |  x86-64, i3-4160T                                 |
| Memory           |  8GB, 78% available                            |
| Java version     |   openjdk 11.0.12 2021-07-20 LTS, zulu11-jre-headless                |
| Devices          | EgWohnzimmerTischlampe 001788010452280f \ EgWohnzimmerStehlampe 001788010859cca0 \ EgWohnzimmerStehlampeSofa 001788010856df32 \ EgWohnzimmerSchrlampe1 00178801085d5e00 \ EgWohnzimmerSchrlampe2 00178801085d5dc2 \ EgGarderobeLampe 0017880104501cd0 \ gaGaragenbeleuchtung b4e3f9fffe266c30 \ UgLagerraumLampe 0017880103374736 \ UgWaschkuecheLampe 00178801045023c1 \ Ember Coordinatorzigbee:coordinator_ember:013E70B9 |

### Logs

```
2021-10-17 17:54:05.586 [ERROR] [b.core.io.console.ConsoleInterpreter] - An error occurred while executing the console command.
java.lang.NullPointerException: null
        at com.zsmartsystems.zigbee.ZigBeeDeviceType.getByValue(ZigBeeDeviceType.java:648) ~[?:?]
        at com.zsmartsystems.zigbee.console.ZigBeeConsoleNodeListCommand.printNode(ZigBeeConsoleNodeListCommand.java:96) ~[?:?]
        at com.zsmartsystems.zigbee.console.ZigBeeConsoleNodeListCommand.process(ZigBeeConsoleNodeListCommand.java:71) ~[?:?]
        at org.openhab.binding.zigbee.console.internal.ZigBeeConsoleCommandExtension.handleZigbeeCommand(ZigBeeConsoleCommandExtension.java:149) ~[?:?]
        at org.openhab.binding.zigbee.console.internal.ZigBeeConsoleCommandExtension.handleCommand(ZigBeeConsoleCommandExtension.java:117) ~[?:?]
        at org.openhab.binding.zigbee.console.internal.ZigBeeConsoleCommandExtension.execute(ZigBeeConsoleCommandExtension.java:89) ~[?:?]
        at org.openhab.core.io.console.ConsoleInterpreter.execute(ConsoleInterpreter.java:55) [bundleFile:?]
        at org.openhab.core.io.console.karaf.internal.CommandWrapper.execute(CommandWrapper.java:78) [bundleFile:?]
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:68) [bundleFile:4.3.3]
        at org.apache.karaf.shell.impl.console.osgi.secured.SecuredCommand.execute(SecuredCommand.java:86) [bundleFile:4.3.3]
        at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:599) [bundleFile:4.3.3]
        at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:526) [bundleFile:4.3.3]
        at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:415) [bundleFile:4.3.3]
        at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:416) [bundleFile:4.3.3]
        at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229) [bundleFile:4.3.3]
        at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59) [bundleFile:4.3.3]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by yuergen** [comment]
The milestone 3.2.0 M4 build does solve this issue. The release [notes](https://github.com/openhab/openhab-distro/releases/tag/3.2.0.M4) state that Z-Smart Systems library has been upgraded to 1.4.1. I can now use the zigbee node command without any exceptions. :smile:
