### ISSUE TITLE
OH 4.1 M4 Devices with a voltage Channel remain unknown: `this.cluster` is null

### ISSUE THREAD

**Issue by rkoshak** [openhab/org.openhab.binding.zigbee#816]
### Outline

After upgrading to OH 4.1 M4 some but not all of my Zigbee devices which previously worked stopped working. They show up in MainUI as unknown.

During the boot the following exception is thrown repeatedly for different nodes:

```
2023-12-05 07:24:56.238 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NullPointerException: Cannot invoke "com.zsmartsystems.zigbee.zcl.clusters.ZclPowerConfigurationCluster.getAttribute(int)" because "this.cluster" is null
        at org.openhab.binding.zigbee.internal.converter.ZigBeeConverterBatteryVoltage.getChannel(ZigBeeConverterBatteryVoltage.java:125) ~[?:?]
        at org.openhab.binding.zigbee.internal.converter.ZigBeeChannelConverterFactoryImpl.getChannels(ZigBeeChannelConverterFactoryImpl.java:82) ~[?:?]
        at org.openhab.binding.zigbee.discovery.ZigBeeDiscoveryService$2.run(ZigBeeDiscoveryService.java:248) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

Only those devices that have a voltage Channel have the problem. In my case that's two battery powered water leak detectors and a bunch of Peanut Plugs which, while being mains powered, has always had battery type Channels though nothing is ever published there.

I've attached the full boot log with the binding in debug.

### Configuration

| Configuration    | Description                                                                    |
|------------------|--------------------------------------------------------------------------------|
| Coordinator used |       HUSZB                                                                          |
| openHAB version  | OH 4.1 M3 to OH 4.1 M4   |
| Hardware         |         VM on Intel CPU  running in Docker                                                                      |
| Memory           |           12 GB                                                                     |
| Java version     |             Whatever comes with the Docker image                                                                  |
| Devices          | 

Not working Devices
- Third Reality Water Leak Alarm: 282C02BFFFE7C35A 
- Third Reality Water Leak Alarm: 282C02BFFFE726CD
- PeanutPlug: 000D6F000A798EE4
- PeanutPlug: 000d6f0005075c02
- PeanutPlug: 000d6f000a79badf
- PeanutPlug: 000d6f00053ac32d
- PeanutPlug: 000d6f0004a86850

Working Devices
- Leviton DG155-1BW Wall Switch: 0022A3000040D061
- Dogain Zigbee Smart Plug: 7CB94C6335C00000
- Dogain Zigbee Smart Plug: 7cb94c6356c60000

### Logs

[openhab.log](https://github.com/openhab/org.openhab.binding.zigbee/files/13561489/openhab.log)

**Comment by rkoshak** [comment]
A sharp eyed person on the [forum](https://community.openhab.org/t/openhab-4-1-milestone-discussion/149502/110) noticed https://github.com/openhab/org.openhab.binding.zigbee/pull/814, perhaps the errors are related to this PR?
