### ISSUE TITLE
Zigbee-Binding: 4.3.0 M4 Error on Smart Plugs

### ISSUE THREAD

**Issue by FranzSchi** [openhab/org.openhab.binding.zigbee#873]
I own a bunch of Smart Plugs with measurement .
Since the update to 4.3.0 M3 Many of them won’t come back online again.

Thank you

![](https://community-openhab-org.s3.dualstack.eu-central-1.amazonaws.com/original/3X/9/4/941a469828c17dc9fad60703bcec22e60b8ff467.png)

````
2024-11-13 10:46:19.755 [ERROR] [ng.zigbee.handler.ZigBeeThingHandler] - A4C138F96D1BA59C: Exception creating channels

java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')

at com.zsmartsystems.zigbee.serialization.DefaultSerializer.appendZigBeeType(DefaultSerializer.java:224) ~[bundleFile:?]

at com.zsmartsystems.zigbee.zcl.field.AttributeReportingConfigurationRecord.serialize(AttributeReportingConfigurationRecord.java:361) ~[bundleFile:?]

at com.zsmartsystems.zigbee.zcl.ZclFieldSerializer.serialize(ZclFieldSerializer.java:39) ~[bundleFile:?]

at com.zsmartsystems.zigbee.zcl.clusters.general.ConfigureReportingCommand.serialize(ConfigureReportingCommand.java:107) ~[bundleFile:?]

at com.zsmartsystems.zigbee.ZigBeeNetworkManager.sendCommand(ZigBeeNetworkManager.java:904) ~[bundleFile:?]

at com.zsmartsystems.zigbee.transaction.ZigBeeTransactionManager.send(ZigBeeTransactionManager.java:452) ~[bundleFile:?]

at com.zsmartsystems.zigbee.transaction.ZigBeeTransactionManager.sendNextTransaction(ZigBeeTransactionManager.java:694) ~[bundleFile:?]

at com.zsmartsystems.zigbee.transaction.ZigBeeTransactionManager.queueTransaction(ZigBeeTransactionManager.java:379) ~[bundleFile:?]

at com.zsmartsystems.zigbee.transaction.ZigBeeTransactionManager.sendTransaction(ZigBeeTransactionManager.java:357) ~[bundleFile:?]

at com.zsmartsystems.zigbee.ZigBeeNetworkManager.sendTransaction(ZigBeeNetworkManager.java:2031) ~[bundleFile:?]

at com.zsmartsystems.zigbee.ZigBeeNode.sendTransaction(ZigBeeNode.java:1061) ~[bundleFile:?]

at com.zsmartsystems.zigbee.ZigBeeEndpoint.sendTransaction(ZigBeeEndpoint.java:615) ~[bundleFile:?]

at com.zsmartsystems.zigbee.zcl.ZclCluster.sendCommand(ZclCluster.java:339) ~[bundleFile:?]

at com.zsmartsystems.zigbee.zcl.ZclCluster.sendCommand(ZclCluster.java:350) ~[bundleFile:?]

at com.zsmartsystems.zigbee.zcl.ZclCluster.setReporting(ZclCluster.java:1870) ~[bundleFile:?]

at com.zsmartsystems.zigbee.zcl.ZclCluster.setReporting(ZclCluster.java:637) ~[bundleFile:?]

at com.zsmartsystems.zigbee.zcl.ZclAttribute.setReporting(ZclAttribute.java:452) ~[bundleFile:?]

at org.openhab.binding.zigbee.internal.converter.ZigBeeConverterMeteringSummationDelivered.updateConfiguration(ZigBeeConverterMeteringSummationDelivered.java:151) ~[bundleFile:?]

at org.openhab.binding.zigbee.handler.ZigBeeThingHandler.doNodeInitialisation(ZigBeeThingHandler.java:421) [bundleFile:?]

at org.openhab.binding.zigbee.handler.ZigBeeThingHandler$1.call(ZigBeeThingHandler.java:244) [bundleFile:?]

at org.openhab.binding.zigbee.handler.ZigBeeThingHandler$1.call(ZigBeeThingHandler.java:1) [bundleFile:?]

at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]

at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]

at java.lang.Thread.run(Thread.java:840) [?:?]

2024-11-13 10:46:19.755 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler ZigBeeThingHandler of thing zigbee:device:62ec522f14:a4c138f96d1ba59c tried updating channel A4C138F96D1BA59C_1_meteringsumdelivered although the handler was already disposed.

2024-11-13 10:46:19.755 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler ZigBeeThingHandler of thing zigbee:device:62ec522f14:a4c138f96d1ba59c tried updating channel A4C138F96D1BA59C_1_meteringsumdelivered although the handler was already disposed.

2024-11-13 10:46:19.755 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler ZigBeeThingHandler of thing zigbee:device:62ec522f14:a4c138f96d1ba59c tried updating channel A4C138F96D1BA59C_1_meteringsumdelivered although the handler was already disposed. 
```

**Comment by cdjackson** [comment]
Closing as complete.
